FROM verlai/verl:vllm011.latest

ENV DEBIAN_FRONTEND=noninteractive
ENV UV_SYSTEM_PYTHON=1
ENV UV_LINK_MODE=copy
ENV UV_FROZEN=1
WORKDIR /workspace

# 安装 uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# aladdin 镜像的sshd 配置
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        openssh-server \
        net-tools \
        vim \
        telnet \
        iputils-ping \
        unzip \
        bzip2 \
        tmux \
        curl \
        git && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y --no-install-recommends nodejs && \
    mkdir -p /var/run/sshd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/*

# clone agent-lightning，使用仓库的pyproject.toml 安装依赖  uv可以调用其中的group，纯pip不可以
RUN git clone --depth 1 https://github.com/microsoft/agent-lightning.git /workspace/agent-lightning

WORKDIR /workspace/agent-lightning
ENV UV_SYSTEM_PYTHON=1
# 同步所有依赖到系统 Python 环境
RUN uv pip install -r pyproject.toml --system \
    --group dev \
    --group experiment \
    --group image \
    --group core-stable \
    --group langchain \
    --group torch-gpu-stable \
    --group trl \
    --group agents \
    --group langchain

# 切换为 PyPI 正式版本
RUN uv pip uninstall --system agentlightning && \
    uv pip install --system agentlightning pymongo swanlab

RUN uv pip install --system vllm==0.11.2


# 构建 Dashboard
RUN cd dashboard && \
    npm ci --prefer-offline --no-audit --progress=false && \
    npm run build && \
    rm -rf /root/.npm

RUN cp -r dashboard /usr/local/lib/python3.12/dist-packages/agentlightning

# 导出环境列表
WORKDIR /workspace
RUN uv pip freeze --system --exclude-editable > /workspace/requirements.txt


# 清理缓存
RUN rm -rf /root/.cache/uv \
         /root/.cache/npm \
         /root/.cache/pip \
         /tmp/* \
         /var/tmp/* && \
    find / -name "*.pyc" -delete 2>/dev/null || true

RUN rm -rf /workspace/agent-lightning

# 暴露端口 aladdin镜像需求
EXPOSE 8080




