FROM verlai/verl:vllm012.latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN apt-get update && \
    apt-get install -y openssh-server net-tools vim telnet iputils-ping unzip bzip2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


EXPOSE 8080
