name: Build AgentLightning Image UV-PIP

on:
  push:
    branches:
      - main
    paths:
      - 'docker/Dockerfile-agl-uv-pip'
      - '.github/workflows/build-agl-uv-pip.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIA }}
          username: ${{ secrets.ALIB }}
          password: ${{ secrets.ALIC }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile-agl-uv-pip
          push: true
          tags: |
            ${{ secrets.ALID }}/agentlightning:0.3.0.post2
          cache-from: type=gha
          cache-to: type=gha,mode=max
